"""Prototype prompt translation logic."""

from __future__ import annotations

from typing import Any, Dict, Optional

from .models import OscillatorSettings, Patch, PatchEnvelope

DEFAULT_WAVETABLES = {
    "airy": "CloudNine",
    "bass": "SubLift",
    "plucky": "NeonPluck",
    "pad": "AuroraPad",
}


def _infer_wavetable_from_prompt(prompt: str) -> str:
    """Naive keyword-based wavetable selection."""
    lower_prompt = prompt.lower()
    for keyword, wavetable in DEFAULT_WAVETABLES.items():
        if keyword in lower_prompt:
            return wavetable
    return "InitSaw"


def build_initial_patch(prompt: str, context: Optional[Dict[str, Any]] = None) -> Patch:
    """Create a first-draft patch using simple heuristics.

    This is a placeholder implementation while LLM integration is under
    development. It demonstrates how prompt text and optional context data
    could be assembled into the structured patch model.
    """

    wavetable = _infer_wavetable_from_prompt(prompt)
    envelope = PatchEnvelope(attack=0.3, decay=0.8, sustain=0.6, release=0.5)

    if context and context.get("mood") == "pad":
        envelope = PatchEnvelope(attack=0.8, decay=1.2, sustain=0.75, release=1.5)

    oscillators = [
        OscillatorSettings(wavetable=wavetable, blend=0.7),
        OscillatorSettings(wavetable="Noise", blend=0.1, detune=3.0, octave=1),
    ]

    return Patch(
        name=f"Draft - {prompt[:32]}",
        oscillators=oscillators,
        envelope=envelope,
        notes="Generated by heuristic prompt engine. Replace with LLM output.",
    )
